apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: grafana
    spec:
      containers:
        - env:
            - name: GF_DATABASE_URL
              value: mysql://root:je_MDML1228gm@grafana_mysqldb:3306/grafana
            - name: GF_INSTALL_PLUGINS
              value: ryantxu-ajax-panel,natel-plotly-panel,bessler-pictureit-panel,larona-epict-panel
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: je_MDML1228grafana
            - name: GF_SERVER_CERT_FILE
              value: /etc/ssl/certs/nginx-selfsigned.crt
            - name: GF_SERVER_CERT_KEY
              value: /etc/ssl/nginx-selfsigned.key
            - name: GF_SERVER_DOMAIN
              value: 52.4.135.44
            - name: GF_SERVER_HTTP_ADDR
              value: 0.0.0.0
            - name: GF_SERVER_PROTOCOL
              value: https
            - name: GF_SERVER_ROOT_URL
              value: https://52.4.135.44/grafana/
          image: grafana
          name: grafana
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /etc/ssl/nginx-selfsigned.key
              name: grafana-claim0
            - mountPath: /etc/ssl/certs/nginx-selfsigned.crt
              name: grafana-claim1
      restartPolicy: Always
      volumes:
        - name: grafana-claim0
          persistentVolumeClaim:
            claimName: grafana-claim0
        - name: grafana-claim1
          persistentVolumeClaim:
            claimName: grafana-claim1
status: {}
